- arrow/src/array/ord.rs
- arrow/src/compute/kernels/merge.rs
It was already used when comparing single-value columns.
CubeStore requires this on compactions to produce correct results.
> Use total order for float comparisons in lexicographical compares

- .github/workflows/integration.yml
- .github/workflows/rust.yml
- arrow/src/compute/kernels/comparison.rs
- parquet/src/file/serialized_reader.rs
N/A
Enable caching of ParquetMetaData in cube.js/arrow-datafusion.
See above.
New api: `SerializedFileReader::new_with_metadata`
> chore: Adds SerializedFileReader::new_with_metadata to avoid reading metadata from file on every invocation

- .github/workflows/integration.yml
- .github/workflows/rust.yml
- arrow/src/compute/kernels/comparison.rs
- parquet/src/file/serialized_reader.rs
N/A
Enable caching of ParquetMetaData in cube.js/arrow-datafusion.
See above.
New api: SerializedFileReader::new_with_metadata
> chore: Adds SerializedFileReader::new_with_metadata to avoid reading metadata from file on every invocation #3

- parquet/src/file/footer.rs
- parquet/src/file/metadata.rs
- parquet/src/file/serialized_reader.rs
N/A
Weight ParquetMetadataCache by metadata size. 
Adds `ParquetMetadata::new_with_size` to construct a ParquetMetadata tracking size. Updates `footer::parse_metadata` to track the metadata (disk) size explicitly.
> feat: Track size for ParquetMetadata

- arrow/src/compute/kernels/cast.rs
This PR implements `Utf8` to `Boolean` cast, allowing bools to be compared with strings.
The set of recognized strings matches PostgreSQL behavior.
> feat: Implement `Utf8` to `Boolean` cast

- arrow/src/array/transform/mod.rs
`extends_nulls` now also resize the `null_buffer` if it necessary.
> chore: Fix bug with extend_nulls

- .github/workflows/rust.yml
This PR locks Rust toolchain in workflows in addition to the recently locked development environment.
> ci: Lock Rust toolchain in workflows

- arrow/src/compute/kernels/cast.rs
This PR adds support for casting `Date32` to `Timestamp`. A related test is included.
> feat: Support casting `Date32` to `Timestamp`

- arrow/src/array/array.rs
- arrow/src/array/ord.rs
- arrow/src/compute/kernels/cast.rs
This PR adds support for casting `Null` to and from other data types. It also adds ordering for `Null` values. Related tests are included.
> feat: Support cast between `Null` and other data types

- arrow/src/datatypes/native.rs
> fix: Missing `from_i64` method for int64

- arrow/src/compute/kernels/comparison.rs
> fix: Escape regex symbols in all versions of like operator

- arrow/src/array/ord.rs
> fix: Natural order for Int96 and Decimal96

- arrow/src/array/array.rs
- arrow/src/array/ord.rs
- arrow/src/compute/kernels/cast.rs
This PR cherry-picks a commit allowing `Null` casting, adding support for `Null` ordering and `Decimal`-`Null` casts on top of it. Related tests are included.
> feat: Support casting from/to `Null`

- arrow/Cargo.toml
- arrow/src/compute/kernels/cast.rs
- arrow/src/util/serialization.rs
This PR alters the way `Float` types are converted to `Utf8`, trimming the ".0" postfix if a float has no fractional part. This is in accordance with how PostgreSQL converts floats to text, and does not affect `Decimal` (numeric) which retain their fractional part even if it is 0.
> fix: Trim ".0" postfix when converting `Float` to `Utf8`

- arrow/src/compute/kernels/cast.rs
This PR adds support for parsing timestamp strings (such as `2024-01-01 00:00:00`) as dates. This is valid in Postgres; time and timezone is ignored. Related test is included.
> feat: Parse timestamp strings as `Date32`

- arrow/src/compute/kernels/arithmetic.rs
This PR adds `powf` function akin to `powf_scalar`, adding support for mathematical exponentiation with arrays. Related test is included.
> feat: Support `powf` for arrays

- arrow/src/alloc/alignment.rs
- arrow/src/array/array_binary.rs
- arrow/src/compute/kernels/cast.rs
- arrow/src/ipc/reader.rs
- dev/release/rat_exclude_files.txt
- parquet/src/record/api.rs
- parquet/src/schema/parser.rs
- parquet/src/util/bit_packing.rs
- parquet/src/util/bit_util.rs
- parquet/src/util/hash_util.rs
- rust-toolchain.toml
```
rustc 1.77.0-nightly (635124704 2024-01-27)
binary: rustc
commit-hash: 635124704849eeead4e3a7bb6e663c5351571d93
commit-date: 2024-01-27
host: aarch64-apple-darwin
release: 1.77.0-nightly
LLVM version: 17.0.6
```
> fix: Backport fixes for rust 1.77

- parquet/Cargo.toml
- parquet/src/basic.rs
- parquet/src/column/page.rs
- parquet/src/column/writer.rs
- parquet/src/file/encryption.rs
- parquet/src/file/footer.rs
- parquet/src/file/metadata.rs
- parquet/src/file/mod.rs
- parquet/src/file/properties.rs
- parquet/src/file/serialized_reader.rs
- parquet/src/file/writer.rs
> Parquet encryption

- .github/workflows/rust.yml
- arrow-flight/Cargo.toml
- arrow/Cargo.toml
- arrow/src/compute/kernels/comparison.rs
- arrow/src/compute/kernels/substring.rs
- arrow/src/ffi.rs
- arrow/src/json/reader.rs
- arrow/src/json/writer.rs
- arrow/src/util/integration_util.rs
- integration-testing/Cargo.toml
- parquet/Cargo.toml
- parquet/src/column/page.rs
- parquet/src/column/writer.rs
- parquet/src/file/encryption.rs
- parquet/src/file/footer.rs
- parquet/src/file/metadata.rs
- parquet/src/file/mod.rs
- parquet/src/file/properties.rs
- parquet/src/file/serialized_reader.rs
- parquet/src/file/writer.rs
- parquet/src/schema/types.rs
- parquet_derive/Cargo.toml
Is was broken in commit 6505f1b1. GHA does not allow empty vector in build matrix, and does not start whole workflow, not just a single broken job
It would just say `The workflow is not valid. .github/workflows/rust.yml (Line: 129, Col: 15): Matrix vector 'rust' does not contain any values`
Like here: https://github.com/cube-js/arrow-rs/actions/runs/10713316185
> Revive CI after misconfigured GHA job

- parquet/src/file/encryption.rs
- parquet/src/file/footer.rs
- parquet/src/file/writer.rs
So now read key sets can be `[Unencrypted, key1, key2]` when starting out.
> feat: add ParquetEncryptionMode, to permit unencrypted files in initial key rotation
